### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by nickmaleao** [ChristopherRogers1991/mycroft-hue#2]
Hello, 

I am trying to use this skill, but every time i start the skills the following error occurs.

I'm using the latest mycroft core submit : release/0.7.20-91-geb0a37c.

> Traceback
> 
>  (most recent call last):
>   File "/home/leonari/mycroft-core/mycroft/skills/core.py", line 101, in load_skill
>     skill = skill_module.create_skill()
>   File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 466, in create_skill
>     return PhillipsHueSkill()
>   File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 94, in __init__
>     self.brightness_step = int(self.config.get('brightness_step'))
> AttributeError: 'NoneType' object has no attribute 'get'

**Comment by ChristopherRogers1991** [comment]
Hello,

Have you completed step five of the setup in the (README)[ChristopherRogers1991/mycroft-hue/blob/master/README.md]? From the error, the config object is None, making me think it wasn't initialized, which I believe happens if that config block doesn't exist.

Best, 

Chris

**Comment by nickmaleao** [comment]
Sorry for not mentioning it, but I've done all the steps described in the readme.

Here's a copy off my .ini file

leonari@orangepipcplus:~/mycroft-core$ cat ~/.mycroft/mycroft.ini

```
[core]
third_party_skills_dir = "~/.mycroft/third_party_skills"

[Mopidy Skill]
mopidy_url = http://localhost:6680

[MediaSkill]
mopidy_url = http://localhost:6680

[PhillipsHueSkill]
verbose = True
brightness_step = 50
color_temperature_step = 1000
default_group = 0
ip = "192.168.1.121"
username = ""

```

**Comment by ChristopherRogers1991** [comment]
Thanks! I'll check it all out more closely when I'm home this evening (currently on mobile). I know there were some changes to the config stuff recently (I believe the main config changed from ini to JSON) and I haven't tested against a recent build.

If you're eager, and want to hand-jam it, I think you could just add a line to the init method (just after the `super(...)` line) to create a dictionary with the same config values, e.g:

```
Self.config = {'ip': <ip>, 'username': ''...}
```

I believe that would get you up and running until I can work out the issue this evening.

**Comment by ChristopherRogers1991** [comment]
Hey @nickmaleao,

It looks like as of [this commit](https://github.com/MycroftAI/mycroft-core/commit/3304474a22e92be505f8c27d79cb700a22390b3f#diff-783c1df3b136d7bf3e26bc50c452b254) mycroft-core as abandoned the .ini files for .conf files (formatted as JSON). They also appear to have changed the default third party skills directory to `~/.mycroft/skills` (see [this](https://github.com/MycroftAI/mycroft-core/blob/2503fb1450d7effcd2fa6c40ce97de5d306b4f89/mycroft/skills/main.py#L34) and [this](https://github.com/MycroftAI/mycroft-core/blob/2503fb1450d7effcd2fa6c40ce97de5d306b4f89/mycroft/configuration/mycroft.conf#L7)).

I am traveling until the new year, and am not able to test this fully, but I've created [this branch](https://github.com/ChristopherRogers1991/mycroft-hue/tree/issues/issue-2) with an updated README, and a small change to handle the verbose boolean correctly with JSON. If you:

1. mkdir ~/.mycroft/skills
2. cd ~/.mycroft/skills
3. git clone git@github.com:ChristopherRogers1991/mycroft-hue.git && git checkout issues/issue-2
4. Create `~/.mycroft/mycroft.conf` with the following contents:
```
{
  "PhillipsHueSkill": {
    "ip": "192.168.1.121",
    "username": "",
    "verbose": true,
    "brightness_step": 50,
    "color_temperature_step": 1000,
    "default_group": 0
  }
}
```
I think that should get you up and running. I tested on a live USB with Ubuntu 16.10, and it all seemed to at least load (the limit of what I am able to test at the moment).

Assuming that works, I imagine you'll need to add blocks to that .conf file for you're other skills as well.

Let me know if that gets you going.

Best,

Chris

**Comment by nickmaleao** [comment]
It works! Thanks!!!  I was able to load the skill, but will only be able to test it later tonight, right now i am at work.

I had to clone the repo with the command: 

git clone -b issues/issue-2 https://github.com/ChristopherRogers1991/mycroft-hue.git

**Comment by nickmaleao** [comment]
The loading problem seems to be resolved, but after trying to do some actions, i see that the command gets routed to the Philips Hue skill but then  a error appears and the execution off the command ends in error.

Seeing that the original issue is resolved , i will open another issue for the new problem.

Best regards.

**Comment by ChristopherRogers1991** [comment]
Changes merged to master with https://github.com/ChristopherRogers1991/mycroft-hue/pull/4.
