### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by zhampu** [ChristopherRogers1991/mycroft-hue#34]
Is the voice command to install this working?

**Comment by ChristopherRogers1991** [comment]
This skill is not in the Mycroft Skills Marketplace, so I don't believe it can be installed with the voice command (it used to be in the marketplace, but the process for getting a skill in has changed a few times, and I haven't kept up). The manual process should still work (see https://github.com/ChristopherRogers1991/mycroft-hue#manual-install).
