### ISSUE TITLE
Any javascript examples?

### ISSUE THREAD

**Issue by playground** [ChristopherRogers1991/mycroft-hue#6]
Are the examples available in JavaScript?

**Comment by ChristopherRogers1991** [comment]
Can you be more specific about what you're looking for? Examples of working with the Phillips Hue lights in JavaScript?

**Comment by playground** [comment]
Hi, I'm new to Myctoft, controlling lights and tv will be good or any interesting javascript examples are good too.

**Comment by playground** [comment]
I'm waiting for mark 1 to arrive.  Would also like to learn how to communicate between my pi3 and mark 1.

**Comment by ChristopherRogers1991** [comment]
For Hue lights and any devices controllable via infrared, this skill and https://github.com/ChristopherRogers1991/mycroft-irsend should work. Note that for the irsend skill, you'll need lirc set up. [The Mycroft docs] (https://docs.mycroft.ai/skills.and.features/adding.skills) should help you get the skills set up with your Mark 1. Feel free to ask any questions here if you have trouble getting them set up.

If you're looking to get into skill development, I think you'll need to pick up Python (see https://docs.mycroft.ai/skill.creation). I don't think you'll be able to directly use JavaScript for this.

As for communication between the pi and the Mark 1, I'm not entirely sure what you mean. The Mark 1 is just the Mycroft service running atop a Debian based Linux, so any standard means of communicating between two computers will be possible.

If you mean you'd like to communicate with Mycroft service, e.g. to issue commands via your own separate service, I think you'll want to see the docs about [the message bus] (https://docs.mycroft.ai/core.overview). This is not something I've personally done, so I unfortunately can't be of much assistance if this is what you're wanting to do. Someone on the Mycroft team, or perhaps someone on slack, may be able to provide more.

Is there anything else I can address for you here?

Best,

Chris

**Comment by playground** [comment]
Thanks Chris, 
Since MyCroft is completely open, I was hoping I can use MyCroft along with Mark 1 to perform STT on the spoken query, then utilize the skills I have already built in Watson platform to process the query and determine the intents.

I'm a Javascript guy and know nothing about Python at this point, I would like to continue to build with Javascript if I have a choice.  I found this here https://www.npmjs.com/package/mycroft but doesn't look like it is active.  

As for communication between Mark 1 and Pi, I saw a video that one can speak to Mark 1 in one room and have it make the announcement from the second Mark 1 in a different room.  Pretty much using it as a intercom.

**Comment by ChristopherRogers1991** [comment]
Ah, for STT, I don't think you'll actually be able to leverage much from Mycroft yet. At the moment, I believe they use Google for STT. They are planning to eventually create their own STT system, but at the moment, it's an empty repo: https://github.com/MycroftAI/openstt.

For the intercom, I believe there is a skill planned, but I don't think it exists yet.
